from google.adk.agents.llm_agent import Agent 
#from google.adk.agents.llm_agent import LoopAgent
#from .tools import contracts_agreements, writ_template, civil_litigation, criminal_litigation, family_law, commercial_templates,criminal_or_civil_litigation
#from validator_agent import validator_agent
from dotenv import loadenv
loadenv()

root_agent = Agent(
    name = "validator_agent",
    description = "Revises the draft generated by the draft agent and corrects it based on precedent cases",
    model = "gemini-2.5-flash",
    instruction = "You are a draft validator agent. You must take relevent precedent cases and revise the draft generated by the draft agent.",
    #tools = [contracts_agreements, writ_template, civil_litigation, criminal_litigation, family_law, commercial_templates,criminal_or_civil_litigation],
    
)